language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - source ./.travis/install_cmake.sh
  - source ./.travis/install_openssl.sh

script:
  - install -d build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC ..
  - make VERBOSE=1
  - make test
